# This is a basic workflow to help you get started with Actions

name: homelab-automation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    container:
      image: alpine:3.22
    steps:
     - uses: actions/checkout@v4
     - name: Install required software
       run: | 
           apk update
           apk add --no-cache curl
           curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
           chmod 700 install-opentofu.sh
           ./install-opentofu.sh --install-method apk
           rm -f install-opentofu.sh
     
     - name: Get Kanye quote
       run: |
           curl https://api.kanye.rest
